#!/command/with-contenv sh

set -eu

. /etc/colors.sh

PREFIX="[s6-rc] [rclone-mount-prepare]-up:"

mkdir -p "${MountPoint}" "${ConfigDir}"

printf '%b\n' "${PREFIX} ${Blue}prepared mount and config directories${Color_Off}"
